(define "perk_t1"
		{"health" "125%"
		}
		{"health_regeneration" "100%"
		}
		{"stamina" "75%"
		}
		{"stamina_regeneration" "100%"
		}
		{"vision" "mp_soldier"
		}
		{"speed" 1.0
		}
		
		{"pistol" lvl_1
		}
		{"smg" lvl_1
		}
		{"mgun" lvl_1
		}
		{"rifle" lvl_1
		}
		{"rocketlauncher" lvl_1
		}
		{"melee" lvl_1
		}
)
(define "perk_t2"
		{"health" "175%"
		}
		{"health_regeneration" "100%"
		}
		{"stamina" "100%"
		}
		{"stamina_regeneration" "100%"
		}
		{"vision" "mp_soldier"
		}
		{"speed" 1.0
		}
		
		{"pistol" lvl_2
		}
		{"smg" lvl_2
		}
		{"mgun" lvl_2
		}
		{"rifle" lvl_2
		}
		{"rocketlauncher" lvl_2
		}
		{"melee" lvl_2
		}
)
(define "perk_t3"
		{"health" "275%"
		}
		{"health_regeneration" "100%"
		}
		{"stamina" "125%"
		}
		{"stamina_regeneration" "100%"
		}
		{"vision" "mp_soldier"
		}
		{"speed" 1.0
		}
		
		{"pistol" lvl_3
		}
		{"smg" lvl_3
		}
		{"mgun" lvl_3
		}
		{"rifle" lvl_3
		}
		{"rocketlauncher" lvl_3
		}
		{"melee" lvl_3
		}
)
(define "perk_t4"
		{"health" "375%"
		}
		{"health_regeneration" "100%"
		}
		{"stamina" "150%"
		}
		{"stamina_regeneration" "100%"
		}
		{"vision" "mp_soldier"
		}
		{"speed" 1.0
		}
		
		{"pistol" lvl_4
		}
		{"smg" lvl_4
		}
		{"mgun" lvl_4
		}
		{"rifle" lvl_4
		}
		{"rocketlauncher" lvl_4
		}
		{"melee" lvl_4
		}
)
(define "perk_t5"
		{"health" "475%"
		}
		{"health_regeneration" "100%"
		}
		{"stamina" "175%"
		}
		{"stamina_regeneration" "100%"
		}
		{"vision" "mp_soldier"
		}
		{"speed" 1.0
		}
		{"stealth"
		}
		
		{"pistol" lvl_5
		}
		{"smg" lvl_5
		}
		{"mgun" lvl_5
		}
		{"rifle" lvl_5
		}
		{"rocketlauncher" lvl_5
		}
		{"melee" lvl_5
		}
)