(define "ability_light"   
	{level "lvl_1"
		{stand
			{accuracy 1.00}
		}
		{squat
			{accuracy 1.50}
		}
		{crawl
			{accuracy 2.00}
		}
		{cover
			{accuracy 2.00}
		}
		{vehicle
			{accuracy 2.00}
		}
	}
	{level "lvl_2"
		{stand
			{accuracy 1.25}
		}
		{squat
			{accuracy 1.75}
		}
		{crawl
			{accuracy 2.25}
		}
		{cover
			{accuracy 2.25}
		}
		{vehicle
			{accuracy 2.25}
		}
	}
	{level "lvl_3"
		{stand
			{accuracy 1.50}
		}
		{squat
			{accuracy 2.00}
		}
		{crawl
			{accuracy 2.50}
		}
		{cover
			{accuracy 2.50}
		}
		{vehicle
			{accuracy 2.50}
		}
	}
	{level "lvl_4"
		{stand
			{accuracy 1.75}
		}
		{squat
			{accuracy 2.25}
		}
		{crawl
			{accuracy 2.75}
		}
		{cover
			{accuracy 2.75}
		}
		{vehicle
			{accuracy 2.75}
		}
	}
	{level "lvl_5"
		{stand
			{accuracy 2.00}
		}
		{squat
			{accuracy 2.50}
		}
		{crawl
			{accuracy 3.00}
		}
		{cover
			{accuracy 3.00}
		}
		{vehicle
			{accuracy 3.00}
		}
	}
)

(define "ability_medium" 
	{level "lvl_1"
		{stand
			{accuracy 0.50}
		}
		{squat
			{accuracy 1.25}
		}
		{crawl
			{accuracy 2.00}
		}
		{cover
			{accuracy 2.00}
		}
		{vehicle
			{accuracy 2.00}
		}
	}
	{level "lvl_2"
		{stand
			{accuracy 0.75}
		}
		{squat
			{accuracy 1.50}
		}
		{crawl
			{accuracy 2.25}
		}
		{cover
			{accuracy 2.25}
		}
		{vehicle
			{accuracy 2.25}
		}
	}
	{level "lvl_3"
		{stand
			{accuracy 1.00}
		}
		{squat
			{accuracy 1.75}
		}
		{crawl
			{accuracy 2.50}
		}
		{cover
			{accuracy 2.50}
		}
		{vehicle
			{accuracy 2.50}
		}
	}
	{level "lvl_4"
		{stand
			{accuracy 1.25}
		}
		{squat
			{accuracy 2.00}
		}
		{crawl
			{accuracy 2.75}
		}
		{cover
			{accuracy 2.75}
		}
		{vehicle
			{accuracy 2.75}
		}
	}
	{level "lvl_5"
		{stand
			{accuracy 1.50}
		}
		{squat
			{accuracy 2.25}
		}
		{crawl
			{accuracy 3.00}
		}
		{cover
			{accuracy 3.00}
		}
		{vehicle
			{accuracy 3.00}
		}
	}
)